"""price unit

Revision ID: 2c957242828b
Revises: 5d8bd791227f
Create Date: 2023-04-20 19:38:23.130948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c957242828b'
down_revision = '5d8bd791227f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
