"""add product column

Revision ID: 3a048f956596
Revises: 9883020175c0
Create Date: 2023-04-20 17:39:28.335407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a048f956596'
down_revision = '9883020175c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('pharmacist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['pharmacist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_create_time'), ['create_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_create_time'))

    op.drop_table('product')
    # ### end Alembic commands ###
