"""first

Revision ID: 9883020175c0
Revises: 
Create Date: 2023-04-13 17:12:10.179312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9883020175c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pharmacist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacist_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_pharmacist_username'), ['username'], unique=True)

    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=200), nullable=True),
    sa.Column('lastname', sa.String(length=200), nullable=True),
    sa.Column('nation_id', sa.String(length=200), nullable=True),
    sa.Column('phone_no', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('pharmacist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['pharmacist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_create_time'), ['create_time'], unique=False)

    op.create_table('pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=200), nullable=True),
    sa.Column('paid_time', sa.DateTime(), nullable=True),
    sa.Column('pharmacist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['pharmacist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pay_create_time'), ['create_time'], unique=False)

    op.create_table('allergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thing', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allergy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allergy_create_time'), ['create_time'], unique=False)

    op.create_table('chief_complain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cc', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chief_complain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chief_complain_create_time'), ['create_time'], unique=False)

    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('med', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_create_time'), ['create_time'], unique=False)

    op.create_table('present_illness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('present_illness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_present_illness_create_time'), ['create_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('present_illness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_present_illness_create_time'))

    op.drop_table('present_illness')
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_create_time'))

    op.drop_table('medicine')
    with op.batch_alter_table('chief_complain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chief_complain_create_time'))

    op.drop_table('chief_complain')
    with op.batch_alter_table('allergy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allergy_create_time'))

    op.drop_table('allergy')
    with op.batch_alter_table('pay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pay_create_time'))

    op.drop_table('pay')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_create_time'))

    op.drop_table('patient')
    with op.batch_alter_table('pharmacist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacist_username'))
        batch_op.drop_index(batch_op.f('ix_pharmacist_email'))

    op.drop_table('pharmacist')
    # ### end Alembic commands ###
